name: Deploy to Google Cloud Bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:

    name: Deploy
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          path: 'www'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: getbatch-website
          service_account_key: ${{ secrets.GCP_DEPLOYER_SERVICE_ACCOUNT }}
          export_default_credentials: true

      - name: Upload Files
        run: |
          rm -rf www/.git
          rm -rf www/.github
          rm www/README.md
          gsutil -m cp -r -z css,js www gs://jarek.lupin.ski
